// Code generated by tygo. DO NOT EDIT.

//////////
// source: graph.go

/**
 * Node is one point in a graph a commit (gitlog), or a symbol from go/types or a language server (explore)
 */
export interface Node {
  id: string;
  label: string;
  kind: string; // "commit" | "function" | "method" | "type" | "interface" | "var" | "const" |
  location?: Location;
  metadata?: { [key: string]: any};
}
/**
 * Location points at a spot in a source file
 */
export interface Location {
  file: string;
  line: number /* int */;
  column: number /* int */;
}
export interface Edge {
  from: string;
  to: string;
  kind: string; // "parent" | "merge" | "calls" | "implements" | "embeds" | "uses-type"
  metadata?: { [key: string]: any};
}
/**
 * Graph is what both engines hand to the frontend.
 */
export interface Graph {
  nodes: Node[];
  edges: Edge[];
}
