// Code generated by tygo. DO NOT EDIT.

//////////
// source: graph.go
/*
Package graph defines the shared types both the gitlog and explore
engines populate — the contract between them.
See docs/decisions/0002-shared-graph-shape.md for why this exists.
*/

/**
 * Node is one point in a graph — a commit (gitlog) or a symbol (explore).
 */
export interface Node {
  id: string;
  label: string;
  kind: string; // "commit" | "function" | "type" | "var" | ...
  metadata: { [key: string]: any }; // engine-specific extras
}
/**
 * Edge is one connection between two nodes.
 */
export interface Edge {
  from: string;
  to: string;
  kind: string; // "parent" | "merge" | "calls" | "implements" | "embeds"
  metadata?: { [key: string]: any };
}
/**
 * Graph is what both engines hand to the frontend.
 */
export interface Graph {
  nodes: Node[];
  edges: Edge[];
}
